import esbuild from "esbuild";
import process from "process";
import { statSync } from "fs";
import builtins from 'builtin-modules'

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
const outfile = 'main.js';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile,
});

// Since esbuild 0.17 the watch mode lives on the context object; a plain
// build() no longer accepts a "watch" option. esbuild reports the errors
// itself, so we only need the exit code.
try {
	if (prod) {
		const started = Date.now();
		await context.rebuild();
		await context.dispose();
		// rebuild() stays silent, so keep the summary build() used to print.
		const kb = (statSync(outfile).size / 1024).toFixed(1);
		console.log(`  ${outfile}  ${kb}kb\n\nDone in ${Date.now() - started}ms`);
	} else {
		await context.watch();
	}
} catch {
	process.exit(1);
}
